std = "roblox"
[rules]
parenthese_conditions = "allow"
incorrect_standard_library_use = "allow"
multiple_statements = "allow"
unused_variable = "warn"
global_usage = "allow"
shadowing = "allow"
unbalanced_assignments = "allow"